In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys
np.set_printoptions(threshold = sys.maxsize)

In [34]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [35]:
x = dataset.iloc[:,2:4].values
y = dataset.iloc[:,4:].values

In [36]:
from sklearn.model_selection import train_test_split

In [37]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state  = 0)

In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.transform(x_test)

In [39]:
from sklearn.svm import SVC

In [40]:
classifier = SVC(kernel = 'rbf')

In [41]:
classifier.fit(X_train,y_train)

C:\Users\adith\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [42]:
classifier.predict(sc.inverse_transform([[19,19000]]))

array([1], dtype=int64)

In [43]:
y_pred = classifier.predict(X_test)

In [44]:
np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),axis = 1)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 0],
       [1, 1],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 1],
       [0,

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [46]:
cm = confusion_matrix(y_pred,y_test)
print(cm)

[[64  3]
 [ 4 29]]


In [47]:
print(accuracy_score(y_pred,y_test))

0.93


In [48]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       0.94      0.96      0.95        67
           1       0.91      0.88      0.89        33

    accuracy                           0.93       100
   macro avg       0.92      0.92      0.92       100
weighted avg       0.93      0.93      0.93       100

